### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by kouohhashi** [react-spring/react-spring#603]
Hi, 
I'm new here.

I installed react-spring by npm install
```
npm install react-spring
```

then, I created a props like these.
```
import { useSpring, animated } from 'react-spring'

let animated_props = useSpring({ opacity: 1, color: 'red' })
or 
const [props, set] = useSpring(() => ({ xy: [0, 0], config: { mass: 10, tension: 550, friction: 140 } }))
```

and i got error.
```
TypeError: Object(...) is not a function
```
I haven't put the props into animated.div yet.

It seems error happened at createAnimatedComponent
node_modules/react-spring/web.js:269
```
  266 | }
  267 | 
  268 | const createAnimatedComponent = Component => {
> 269 |   const AnimatedComponent = forwardRef((props, _ref) => {
  270 |     const forceUpdate = useForceUpdate();
  271 |     const mounted = useRef(true);
  272 |     const propsAnimated = useRef(null);
```
My versions are 
"react": "^16.0.0",
"react-spring": "^8.0.18"
Node: v8.10.0

Could you give me a hint?
Thanks in advance.

Editted!
the error happens only by ```import { useSpring, animated } from 'react-spring'```

**Comment by drcmda** [comment]
could you check the react version? 16.0.0 could include 16 plain, that would be too old for hooks. the code looks alright to me.

**Comment by kouohhashi** [comment]
It works with react 16.8.4.
Thanks!
