### ISSUE TITLE
Property 'children' does not exist on animated(XXX) components

### ISSUE THREAD

**Issue by brunolemos** [react-spring/react-spring#508]
~After my latest PRs the console now have zero errors but the app still doesn't work :( 
It's not rendering most components.~

~Maybe some change that was made on `createAnimatedComponent`?~

I'm getting this typescript error on vscode after migrating to v8:

```
Property 'children' does not exist on type 'IntrinsicAttributes & ViewProps & RefAttributes<View>'
```

![image](https://user-images.githubusercontent.com/619186/52385430-aaade800-2a68-11e9-94d2-d33287541f84.png)

**Comment by drcmda** [comment]
it has to be this: https://github.com/react-spring/react-spring/blame/7b49a793356c32c3d76e5aedd5155e8a6a344741/src/animated/createAnimatedComponent.js#L43

is there a quick way for me to test react-native?

**Comment by brunolemos** [comment]
There's https://snack.expo.io, similar to codesandbox

But since you will need to edit a dependency I suppose running locally is better

**Comment by drcmda** [comment]
Could give me a quick intro of the commands i need to run to set this up? I thought RN doesn't have hooks yet. I want to give this some priority, would suck to let devhub hang.

**Comment by brunolemos** [comment]
You can use `react-native-web` on codesandbox instead: https://codesandbox.io/s/5k2x0j6x1p 

But don't spend time on this yet, I need to confirm it's nothing on my code

**Comment by brunolemos** [comment]
My `useTransition` call was still wrong, made #511 

Now it's working!

**Comment by brunolemos** [comment]
I'll leave this open because the type error from the title still exists

**Comment by drcmda** [comment]
Ah, it's a type error. That's a relief :)
